### ISSUE TITLE
RuntimeError: Preprocess command failed to execute successfully: ['use poker_player']

### ISSUE THREAD

**Issue by zhiyuanc2001** [princeton-nlp/intercode#11]
Hello, thanks for your outstanding job!
When I run the scripts/expr_react.sh
> python -m experiments.eval_react \
    --data_path ./data/sql/spider/ic_spider_dev.json \
    --env sql \
    --image_name docker-env-sql \
    --log_dir logs/experiments/sql_gpt3test \
    --max_turns 5 \
    --verbose

I encounter the error:

> Traceback (most recent call last):
  File "/data/home/miniconda3/envs/intercode/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/miniconda3/envs/intercode/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/data_creation/intercode/experiments/eval_react.py", line 195, in <module>
    expr_wrapper.run_expr()
  File "/data/home/data_creation/intercode/experiments/eval_react.py", line 101, in run_expr
    self.env.reset(idx)
  File "/data/home/data_creation/intercode/intercode/envs/ic_env.py", line 150, in reset
    raise RuntimeError(f"Preprocess command failed to execute successfully: {self.preprocess(self.record)}")
RuntimeError: Preprocess command failed to execute successfully: ['use poker_player']

It seems that the problem is caused by function:
```python
def preprocess_sql(record: Dict) -> List:
          db = record["db"]
          print(f"db {db}")
          return [f"use {db}"]
```

And the error is raised in
```python
        if self.preprocess is not None:
            preprocess_cmds = self.preprocess(self.record)
            for cmd in preprocess_cmds:
                self.exec_action(cmd)
                if not self.info[ACTION_EXEC]:
                    raise RuntimeError(f"Preprocess command failed to execute successfully: {self.preprocess(self.record)}")
```

Additionally, I find `function exec_action` is not implement and the `self.info = {'action_executed': False}` .
```python
        if self.preprocess is not None:
            # self.info is *{}*
            preprocess_cmds = self.preprocess(self.record)
            for cmd in preprocess_cmds:
                self.exec_action(cmd)
               # self.info is *{'action_executed': False}*
                if not self.info[ACTION_EXEC]:
                    raise RuntimeError(f"Preprocess command failed to execute successfully: {self.preprocess(self.record)}")
```

So how can I solver the problem, or is there anything I missed? Appreciate for your response. :-)

**Comment by zhiyuanc2001** [comment]
Additionally, when I run:
```bash
python run_demo.py sql
```

The InterCode SQL environment seems starting successfully and a CLI interpreter appears:
```bash
INFO     Loaded dataset from ./data/sql/bird/ic_bird.json                                    ic_env.py:53
INFO     Verifying preprocess function...                                                    ic_env.py:61
INFO     Connected to `docker-env-sql_ic_ctr` container                                      ic_env.py:78
INFO     Environment Initialized                                                             ic_env.py:80
INFO     * Note *: `reset` should be explicitly called to load new task episode              ic_env.py:82
INFO     -------------                                                                      ic_env.py:129
         New task episode initialized                                                                    
INFO     Query: Among the superheroes from Marvel Comics, how many of them have blue eyes?  ic_env.py:134
INFO     Gold: SELECT COUNT(T1.id) FROM superhero AS T1 INNER JOIN publisher AS T2 ON       ic_env.py:135
         T1.publisher_id = T2.id INNER JOIN colour AS T3 ON T1.eye_colour_id = T3.id WHERE               
         T2.publisher_name = 'Marvel Comics' AND T3.colour = 'Blue'
```

**Comment by zhiyuanc2001** [comment]
OK, when I change data_path in bash from `./data/sql/spider/ic_spider_dev.json` to `./data/sql/bird/ic_bird.json `, it runs successfully.

**Comment by zhiyuanc2001** [comment]
Sorry to interrupt. I change and rebuild the docker image, and the problem is tackled successfully. :-)
