### ISSUE TITLE
Docker image not found

### ISSUE THREAD

**Issue by oximi123** [princeton-nlp/intercode#13]
When I run the following scripts:

`# SQL Call
# python -m experiments.eval_n_turn \
#     --data_path ./data/sql/spider/ic_spider_dev.json \
#     --dialogue_limit 5 \
#     --env sql \
#     --image_name docker-env-sql \
#     --log_dir logs/experiments \
#     --max_turns 10 \
#     --policy chat \
#     --template game_sql \
#     --model gpt-3.5-turbo
#     --handicap 
#     --verbose `

It throws an exeception that tells me the docker image is not found:

`(intercode) user@ubuntu:~/botao/intercode-master$ python main.py 
Traceback (most recent call last):
  File "/home/user/botao/intercode-master/main.py", line 11, in <module>
    from experiments.policies import (
  File "/home/user/botao/intercode-master/experiments/policies.py", line 5, in <module>
    from .utils import ACTION_PARSER_MAP, PROMPT_MAP, CompletionGPT, ChatGPT, PalmChat, PalmCompletion, HFChat
  File "/home/user/botao/intercode-master/experiments/utils/__init__.py", line 20, in <module>
    from .open_api import (
  File "/home/user/botao/intercode-master/experiments/utils/open_api.py", line 13, in <module>
    assert(access_token)
AssertionError
(intercode) user@ubuntu:~/botao/intercode-master$ vim experiments/utils/open_api.py 
(intercode) user@ubuntu:~/botao/intercode-master$ python main.py 
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/images/docker-env-sql/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/botao/intercode-master/main.py", line 215, in <module>
    expr_wrapper = ExperimentWrapper(args)
  File "/home/user/botao/intercode-master/main.py", line 55, in __init__
    self.env = SqlEnv(image_name=args.image_name,
  File "/home/user/botao/intercode-master/intercode/envs/sql/sql_env.py", line 27, in __init__
    super(SqlEnv, self).__init__(image_name, **kwargs)
  File "/home/user/botao/intercode-master/intercode/envs/ic_env.py", line 77, in __init__
    self.container = get_container(self.container_name, self.image_name, **kwargs)
  File "/home/user/botao/intercode-master/intercode/utils/utils.py", line 48, in get_container
    image = client.images.get(image_name)
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/models/images.py", line 333, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/user/anaconda3/envs/intercode/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/docker-env-sql/json: Not Found ("No such image: docker-env-sql:latest")`

**Comment by kingb12** [comment]
I ran into this issue as well, the problem for me was that the `sql` container in `setup.sh` requires docker compose, so if you don't have that installed, that image isn't created successfully. Installing docker compose and then running just that line from `setup.sh` resolved that portion (you may then need to add some items to `keys.cfg` for other errors). I also had to change the command to `docker compose -f docker/sql-docker-compose.yml up -d` (removing the dash), but this probably depends on how you install the compose plugin and your environment.
